# Generated by Django 3.0.5 on 2021-03-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20210329_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
